// 
// Startup; entrypoint, C/C++ runtime initialisation.
// 

#include <stdint.h>

#include <CMSIS/S32K144.h>

#include "CC16.h"

extern "C" void main();

//
// Markers generated by the linker script.
//
extern uint32_t __data_start;
extern uint32_t __data_end;
extern uint32_t __data_load;
extern uint32_t __bss_start;
extern uint32_t __bss_end;
extern uint32_t __heap_start;

typedef void (*func_t)();
extern func_t __preinit_array_start[];
extern func_t __preinit_array_end[];
extern func_t __init_array_start[];
extern func_t __init_array_end[];
extern func_t __fini_array_start[];
extern func_t __fini_array_end[];

//
// Copy non-constant initialised data to SRAM.
//
static void
copy_data() 
{
    auto src = &__data_load;
    auto dst = &__data_start;

    while(dst < &__data_end) {
        *dst++ = *src++;
    }
}

//
// Zero uninitialised data.
//
static void
zero_bss() 
{
    auto dst = &__bss_start;

    while (dst < &__bss_end) {
        *dst++ = 0;
    }
}

//
// Run global static constructors / init functions.
//
static void
call_init_funcs() 
{
    for (auto pfunc = __preinit_array_start;
         pfunc < __preinit_array_end;
         pfunc++) {
        (*pfunc)();
    }

    for (auto pfunc = __init_array_start;
         pfunc < __init_array_end;
         pfunc++) {
        (*pfunc)();
    }
}

//
// Run global static destructors / fini functions.
//
static void
call_fini_funcs()
{
    for (auto pfunc = __fini_array_start;
         pfunc < __fini_array_end;
         pfunc++) {
        (*pfunc)();
    }
}

//
// Entrypoint from reset.
//
extern "C" void
Reset_Handler(void)
{
    // early init, required for C/C++ to work correctly
    copy_data();
    zero_bss();

    // run global constructors
    call_init_funcs();

    // start 1kHz timer tick 
    SysTick_Config((CC16::Clocks::CORE_CLK) / 1000);

    // run application
    main();

    // run global destructors
    call_fini_funcs();

    // stop (should reset here?)
    while (true);
}